---
format:
  html:
    subtitle: | 
      The weighting structure for metrics that is implied by the Index's data
      model.
source_document: https://index.bsg.ox.ac.uk/posts/implied_weighting/
order: 113
---

# Implied weighting structure {#sec-implied_weighting}

As discussed in the section on data aggregation (@sec-data_aggregation),
the Index uses a simple mean for aggregating through the levels of the data
model to calculate Index and its components. With the exception of the
BTI/SGI scaling discussed in the section on  re-scaling and transformation
(@sec-rescaling_transformation), there is no active (re-)weighting of the data
at any stage of the Index calculation.

Based on the structure of the data model we can calculate an implied weighting
for the individual metrics and sub-components of the model, this is presented
in the table below. However, each country has its own pattern of missing data
and therefore the actual weighting of an individual metric on a country’s
scores will vary depending on what data is does and does not have.

The implicit weighting for a metric is calculated as follows:

- Each domain has a within-index weight of 25% as the Index is a simple mean of
  the four domain scores.
- For the public policy domain each theme has a within-domain weight of 20% as
  the domain score is calculated as an average of the five theme scores, for the
  themes in the other three domains their within-domain weight is 25% as these
  domains have four themes contributing to the calculation of their score.
- Each indicator has a within-theme weight calculated as the inverse of the
  number of indicators in their theme.
- Each metric has a within-indicator weight calculated as the inverse of the
  number of metrics in their theme.
- The overall total implied weight for a metric is calculated as the product
  of its associated within-indicator weight, within-theme weight, within-domain
  weight and within-index weight.

The implied weights for individual metrics range from 0.179% for the metrics
in the data availability indicator to 6.25% for the three metrics which are the
sole metrics used to calculate the border services, procurement, and technology
& workplaces themes. In total there are 17 metrics with an implied weight of
greater than 2%, collectively they have a combined weight of 52.1%. There are
25% metrics with an implied weight of less than 0.25%, collectively they have a
combined weight of 8.2%.

:::{.landscape}

```{r}
#| label: tbl-imp-weights
#| tbl-cap: Implicit weighting of metrics

source("R/out_table.R")

data_structure <- readr::read_csv(
  "data/bipa2024_data_structure.csv",
  show_col_types = FALSE
)

metrics <- data_structure |>
  dplyr::filter(level == "metric") |>
  dplyr::mutate(
    indicator = floor(structure_id),
    theme = floor(structure_id / 100) * 100,
    domain = floor(structure_id / 10000) * 10000
  )

metric_wgts <- metrics |>
  # counts of metrics by indicator
  dplyr::count(domain, theme, indicator, name = "n_met") |>
  dplyr::left_join(
    metrics |>
      dplyr::distinct(domain, theme, indicator) |>
      dplyr::count(domain, theme, name = "n_ind"),
    by = c("domain", "theme")
  ) |>
  dplyr::left_join(
    metrics |>
      dplyr::distinct(domain, theme) |>
      dplyr::count(domain, name = "n_thm"),
    by = c("domain")
  ) |>
  dplyr::mutate(
    n_dom = {
      metrics |>
        dplyr::distinct(domain) |>
        nrow()
    },
    wgt_met = 1 / n_met,
    wgt_ind = 1 / n_ind,
    wgt_thm = 1 / n_thm,
    wgt_dom = 1 / n_dom,
    wgt_tot = wgt_met * wgt_ind * wgt_thm * wgt_dom
  )

wgts_out <- metrics |>
  dplyr::left_join(metric_wgts, by = c("domain", "theme", "indicator")) |>
  dplyr::left_join(
    data_structure |>
      dplyr::select(indicator = structure_id, label_ind = label),
    by = "indicator"
  ) |>
  dplyr::left_join(
    data_structure |>
      dplyr::select(theme = structure_id, label_thm = label),
    by = "theme"
  ) |>
  dplyr::left_join(
    data_structure |>
      dplyr::select(domain = structure_id, label_dom = label),
    by = "domain"
  ) |>
  dplyr::mutate(
    label_dom = glue::glue("{label_dom} ({scales::percent(wgt_dom, 1)})"),
    label_thm = glue::glue("{label_thm} ({scales::percent(wgt_thm, 1)})"),
    label_ind = glue::glue("{label_ind} ({scales::percent(wgt_ind, 0.1)})")
  ) |>
  dplyr::select(
    structure_id,
    label_dom,
    label_thm,
    label_ind,
    label,
    wgt_met,
    wgt_tot
  )

wgts_out |>
  dplyr::arrange(structure_id) |>
  dplyr::mutate(
    label_dom = dplyr::if_else(
      label_dom != dplyr::lag(label_dom, default = ""),
      label_dom,
      ""
    ),
    label_thm = dplyr::if_else(
      label_thm != dplyr::lag(label_thm, default = ""),
      label_thm,
      ""
    ),
    label_ind = dplyr::if_else(
      label_ind != dplyr::lag(label_ind, default = ""),
      label_ind,
      ""
    )
  ) |>
  gt::gt() |>
  gt::tab_options(latex.use_longtable = TRUE) |>
  gt::cols_hide(structure_id) |>
  gt::cols_align(align = "left", columns = tidyselect::starts_with("label")) |>
  gt::cols_label(
    label_dom ~ "Domain",
    label_thm ~ "Theme",
    label_ind ~ "Indicator",
    label ~ "Metric",
    wgt_met ~ "Metric weight",
    wgt_tot ~ "Overall weighting"
  ) |>
  gt::cols_width(
    label_dom ~ gt::pct(20),
    label_thm ~ gt::pct(20),
    label_ind ~ gt::pct(20),
    label ~ gt::pct(25),
    wgt_met ~ gt::pct(8),
    wgt_tot ~ gt::pct(7)
  ) |>
  gt::fmt_percent(columns = c(wgt_met, wgt_tot)) |>
  gt::tab_footnote(
    footnote = paste(
      "Percentages in brackets indicate the relative weight for the domain,",
      "theme or indicator within its particular part of the Blavatnik Index's",
      "data structure. Domains and themes each have a relative weight of 25%",
      "since there are four domains that contribute to the overall Index",
      "score. Some themes have only one indicator and therefore that indicator",
      "has a relative weight of 100%, whereas other themes may be made up of",
      "two indicators in which case each indicator has a relative wieght of",
      "50%."
    ),
    locations = gt::cells_column_labels(
      columns = c(label_dom, label_thm, label_ind)
    )
  ) |>
  gt::tab_footnote(
    footnote = paste(
      "The metric weight column indicates the relative weight of the metric",
      "within its parent indicator. This weight is calculated as the simple",
      "reciprocal of the total number of metrics that contribute to that",
      "indicator (e.g. if an indicator has 3 metrics contributing to it the",
      "metric weight is calculated as 1/3, or 33.3%)."
    ),
    locations = gt::cells_column_labels(columns = wgt_met)
  ) |>
  gt::tab_footnote(
    footnote = paste(
      "The overall weights are those that would apply if a country had data",
      "all 82 metrics that are used to calculate the Blavatnik Index of Public",
      "Administration 2024. In practice the weighting for each metric varies",
      "for each country according to its pattern of missing data.",
      "The overall weight is calculated as the product of all the relative",
      "weights that apply to a metric throughout the Blavatnik Index data",
      "structure. For example the overall metric weight for the metric",
      "'Open government and data portals' is calculated as the domain weight",
      "(25%) multiplied by the theme weight (25%) multiplied by the indicator",
      "weight (33.3%) multiplied by the metric weight (50%): 25% * 25% *",
      "33.3% * 50% = 1 / (4 * 4 * 3 * 2) = 1 / 96 = 1.04%"
    ),
    locations = gt::cells_column_labels(columns = wgt_tot)
  ) |>
  out_table(width = 1000)

```

:::